// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.lahcencodes.proto;

public interface VideoStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lahcencodes.proto.VideoStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.lahcencodes.proto.Video videos = 1;</code>
   */
  java.util.List<com.lahcencodes.proto.Video> 
      getVideosList();
  /**
   * <code>repeated .com.lahcencodes.proto.Video videos = 1;</code>
   */
  com.lahcencodes.proto.Video getVideos(int index);
  /**
   * <code>repeated .com.lahcencodes.proto.Video videos = 1;</code>
   */
  int getVideosCount();
  /**
   * <code>repeated .com.lahcencodes.proto.Video videos = 1;</code>
   */
  java.util.List<? extends com.lahcencodes.proto.VideoOrBuilder> 
      getVideosOrBuilderList();
  /**
   * <code>repeated .com.lahcencodes.proto.Video videos = 1;</code>
   */
  com.lahcencodes.proto.VideoOrBuilder getVideosOrBuilder(
      int index);
}
